### ISSUE TITLE
Converting function declarations into function expressions

### ISSUE THREAD

**Issue by CMCDragonkai** [balena-io-modules/ometa-js#13]
I've noticed that function declarations gets converted into function expressions, is this necessary? I was surprised by this behaviour because it meant that my original function declarations were no longer considered "constructors", and my debugging output I could not get the name of the function constructor anymore.

And I can't even get around this by naming my functions either like:

```
var LetT = function LetT () {};
```

Which is valid javascript, but gives back `SyntaxError: match failed`.

Is the ometa compiler actually parsing the Javascript as well? That's strange, as parts of Javascript might not be working, like the above hybrid declaration and expression.

I would prefer declarations to stay declarations, and expressions to stay expressions, so it's more explicit and understandable.

Doing this also seems to prevent us from being able to match against the function constructors themselves. Consider the possibility of tokens being represented by javascript function constructed objects, the later parser can just try to match a `AssignT` could then be implemented using `instanceof AssignT`.

Thus approaching usability similar to Haskell's algebraic data types.

**Comment by Page-** [comment]
The javascript is parsed and translated as part of the OMeta compilation, this is due to being able to embed javascript snippets within the OMeta and the OMeta compilation having to understand and interact with it, I've opened a PR which will fix the case of `var LetT = function LetT () {};` and will keep the function names intact in the output - hopefully this should fix things for your use case

**Comment by Page-** [comment]
I've published support for this in 1.4.0
