### ISSUE TITLE
OMeta error handler

### ISSUE THREAD

**Issue by CMCDragonkai** [balena-io-modules/ometa-js#9]
In the error handler we currently get something like:

```
err.OMeta = { idx: 0, line: 1, col: 0 }
```

Is it possible to give us a way of knowing which production rule was the one that failed? Perhaps even a stack trace of the production rule, so we can know how deep the production rule went before failing?

**Comment by Page-** [comment]
Sadly it's not that easy due to the backtracking nature of OMeta meaning that it's not possible to know which rule was the one that was meant to succeed (as there are usually multiple possible branches, and any of them might be "the one").

What you can do is to enable branch tracking and see what branches are tracked

``` coffeescript
grammar = OmetaGrammar.createInstance()
grammar.branches = {
    RuleName: true,
    AnotherRule: true
}
grammar._enableBranchTracking(grammar.branches);
grammar.matchAll(input, 'Process');
branches = grammar._getBranches()
console.log(branches[err.OMeta.idx])
```

You might well find that you need to backtrack from the idx that the error happened to find a tracked rule (since it tracks where the rule started matching).  As for the grammar.branches object, you can use it with the hinter module to generate autocomplete (sadly I don't have an example available, but if this is useful to you I can try to get one sorted).
